### ISSUE TITLE
Initialization fails when creating leaf node

### ISSUE THREAD

**Issue by mpskovvang** [memsql/deployment-docker#13]
> Adding node 127.0.0.1:3307 to cluster
> Error 1045: Access denied for user 'root'@'localhost' (using password: YES)

However, when starting the container again, the database starts up as expected, but without the root password. Apparently, the password from the environment is not configured.

Docker Compose example with `LICENSE_KEY` in `.env` file:

```
services:
  singlestore:
    image: singlestore/cluster-in-a-box:alma-8.0.17-0553658f69-4.0.11-1.15.3
    environment:
      ROOT_PASSWORD: "local"
      START_AFTER_INIT: "Y"
    env_file:
      - .env
 ```
