### ISSUE TITLE
Getting access denied when MemSQL tries to execute init.sql

### ISSUE THREAD

**Issue by mxsoftwarelabs** [memsql/deployment-docker#2]
Docker compose:
  ```
version: '2'

volumes:
  memsql-ciab-data:

services:

db:
    image: memsql/cluster-in-a-box
    restart: always
    volumes:
      - ./init.sql:/init.sql
      - memsql-ciab-data:/var/lib/memsql
    environment:
      - LICENSE_KEY=${MEMSQL_LICENSE_KEY}
      - ROOT_PASSWORD=${MEMSQL_ROOTPASSWORD}
    ports:
      - 3306:3306
      - 9000:9000
```
Error:
```
db_1                | 2020-12-13 03:49:57.712151 Running /init.sql...
db_1                | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
db_1                | Traceback (most recent call last):
db_1                |   File "/startup", line 108, in <module>
db_1                |     init_cluster()
```

I am able to connect to the MemSQL instance with the password I have set as ROOT_PASSWORD and I can see the value of root password matching one provided when I inspect the running docker using docker dashboard.
